<a href="https://colab.research.google.com/github/Namesakenberg/deep_learning/blob/main/convolution_from_scratch_greyscale_and_RGB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# convolution and max pooling from scratch for a greyscale image

In [2]:
import pandas as pd
import numpy as np

In [3]:
def my_convolution(image,kernel,padding,strides):
  pad_img = np.pad(image, ((padding, padding),(padding, padding)), mode='constant')

  image_h , image_w = pad_img.shape
  kernel_h , kernel_w = kernel.shape

  output = np.zeros(((image_h-kernel_h)//strides+1, (image_w-kernel_w)//strides+1))
  output_h,output_w = output.shape

  for i in range(0,output_h,strides):
    for j in range(0,output_w,strides):
      output[i,j] = np.sum(pad_img[i:i+kernel_h,j:j+kernel_w]*kernel)
  return output

In [4]:
image = np.array([
    [1, 2, 3, 0, 1],
    [0, 1, 2, 3, 2],
    [3, 0, 1, 2, 1],
    [2, 1, 3, 0, 0],
    [1, 2, 0, 1, 2]
])


kernel =np.array([ [0, 1, 0],
                   [1, -4, 1],
                   [0, 1, 0]])

feature_map = my_convolution(image,kernel,1,1)

In [5]:
print(feature_map)

[[ -2.  -3.  -8.   7.  -2.]
 [  5.   0.   0.  -6.  -3.]
 [-10.   6.   3.  -3.   0.]
 [ -3.   3. -10.   6.   3.]
 [  0.  -6.   6.  -2.  -7.]]


In [6]:
def my_max_pooling(feature_map , filter ,padding , strides):
  if strides ==0 :
    strides = filter
  if padding>0:
    feature_map = np.pad(feature_map , ((padding,padding),(padding,padding)) , mode = 'constant')

  map_height,map_width = feature_map.shape
  filter_height =filter
  filter_width = filter

  max_pooling = np.zeros((
    (map_height - filter_height)//strides + 1,
    (map_width - filter_width)//strides + 1
))

  pool_rows , pool_cols = max_pooling.shape
  for i in range(pool_rows):
    for j in range(pool_cols):
      start_i=i*strides
      start_j = j*strides
      max_pooling[i,j] = np.max(feature_map[start_i:start_i+filter_height , start_j:start_j+filter_width])
  return max_pooling



In [7]:
print(my_max_pooling(feature_map,2,0,2))

[[5. 7.]
 [6. 6.]]


In [8]:
print(my_max_pooling( np.array([
    [1, 2, 3, 0, 1],
    [0, 1, 2, 3, 2],
    [3, 0, 1, 2, 1],
    [2, 1, 3, 0, 0],
    [1, 2, 0, 1, 2]
]),2,0,2))

[[2. 3.]
 [3. 3.]]


# convolution on an rgb image

In [45]:

image = np.array([
    [[1, 0, 2], [2, 1, 1], [3, 2, 0], [0, 1, 1], [1, 0, 2]],
    [[0, 1, 0], [1, 0, 1], [2, 2, 2], [3, 1, 3], [2, 0, 1]],
    [[3, 0, 2], [0, 1, 0], [1, 0, 1], [2, 2, 2], [1, 0, 0]],
    [[2, 1, 1], [1, 0, 2], [3, 3, 1], [0, 1, 0], [0, 2, 1]],
    [[1, 2, 2], [2, 1, 0], [0, 0, 1], [1, 2, 2], [2, 1, 1]]
])


In [46]:
kernel = kernel = np.array([
    [[0, 1, 0], [1, -1, 1], [0, 1, 0]],
    [[1, 0, 1], [0, -1, 0], [1, 0, 1]],
    [[0, 1, 0], [1, 1, 1], [0, 1, 0]]
])


In [75]:
def my_rgb_conv(image,kernel,padding,strides):

  image = np.pad(image,((padding,padding),(padding,padding),(0,0)),mode='constant')

  image_height , image_width , image_channels = image.shape

  kernel_height , kernel_width,kernel_channels = kernel.shape

  output_matrix_height = (image_height - kernel_height)//strides + 1
  output_matrix_width = (image_width - kernel_width)//strides +1
  output_matrix  = np.zeros((output_matrix_height , output_matrix_width))

  for i in range(0,output_matrix_height):
    for j in range(0,output_matrix_width):
      x=i*strides
      y=j*strides
      output_matrix[i,j] = np.sum(image[x:x+kernel_height , y:y+kernel_width ] * kernel)

  return output_matrix


In [74]:
print(my_rgb_conv(image=image , kernel=kernel, padding=1 , strides =1))

[[ 4. 10.  9. 14.  5.]
 [11.  9. 14. 14. 13.]
 [ 3. 18. 15. 14. 12.]
 [14. 11.  9. 12.  7.]
 [ 2. 10.  7.  6.  2.]]


In [76]:
# using tensorflow and keras

import tensorflow
from tensorflow import keras
from tensorflow.keras import models , layers
from tensorflow.keras.models import Sequential

input_shape = (100,100,3)
model = Sequential()
model.add(layers.Input(shape=input_shape))

model.add(layers.Conv2D(16,(3,3),padding="same",strides = 1, activation='relu'))
model.add(layers.MaxPooling2D(pool_size=(2,2),strides=2))

model.add(layers.Conv2D(32 , (3,3) , padding="same" , strides=1,activation='relu'))
model.add(layers.MaxPooling2D(pool_size=(2,2),strides =2 ))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 100, 100, 16)   │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 50, 50, 16)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 50, 50, 32)     │         4,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 25, 25, 32)     │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,088 (19.88 KB)

 Trainable params: 5,088 (19.88 KB)

 Non-trainable params: 0 (0.00 B)

In [80]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import models,layers
from tensorflow.keras.models import Sequential

model= Sequential()
image_shape = (100,100,3)
model.add(layers.Input(shape = image_shape))

model.add(layers.Conv2D(16 , (3,3) , padding = "same" , strides = 1 ,activation = "relu"))
model.add(layers.MaxPool2D((2,2),strides =2))

model.add(layers.Conv2D(32,(3,3),padding="same",strides=1,activation="relu"))
model.add(layers.MaxPool2D((2,2),strides=2))

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_4 (Conv2D)               │ (None, 100, 100, 16)   │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 50, 50, 16)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 50, 50, 32)     │         4,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 25, 25, 32)     │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,088 (19.88 KB)

 Trainable params: 5,088 (19.88 KB)

 Non-trainable params: 0 (0.00 B)