<a href="https://colab.research.google.com/github/Namesakenberg/deep_learning/blob/main/Next_word_prediction_using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
with open('/content/alice_in_wonderland.txt','r') as file:
  content = file.read()
print(content)

Alice's Adventures in Wonderland

                ALICE'S ADVENTURES IN WONDERLAND

                          Lewis Carroll

               THE MILLENNIUM FULCRUM EDITION 3.0




                            CHAPTER I

                      Down the Rabbit-Hole


  Alice was beginning to get very tired of sitting by her sister
on the bank, and of having nothing to do:  once or twice she had
peeped into the book her sister was reading, but it had no
pictures or conversations in it, `and what is the use of a book,'
thought Alice `without pictures or conversation?'

  So she was considering in her own mind (as well as she could,
for the hot day made her feel very sleepy and stupid), whether
the pleasure of making a daisy-chain would be worth the trouble
of getting up and picking the daisies, when suddenly a White
Rabbit with pink eyes ran close by her.

  There was nothing so VERY remarkable in that; nor did Alice
think it so VERY much out of the way to hear the Rabbit say to
itself, `Oh d

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts((content.split('\n')))

tokenizer.word_index

{'the': 1,
 "'": 2,
 'and': 3,
 'to': 4,
 'a': 5,
 'she': 6,
 'it': 7,
 'of': 8,
 'said': 9,
 'i': 10,
 'alice': 11,
 'in': 12,
 'you': 13,
 'was': 14,
 'that': 15,
 'as': 16,
 'her': 17,
 'at': 18,
 'on': 19,
 'all': 20,
 'with': 21,
 'had': 22,
 'but': 23,
 'for': 24,
 'so': 25,
 'be': 26,
 'very': 27,
 'not': 28,
 'what': 29,
 'this': 30,
 'they': 31,
 'little': 32,
 'he': 33,
 'out': 34,
 'is': 35,
 'one': 36,
 'down': 37,
 'up': 38,
 'if': 39,
 'his': 40,
 'then': 41,
 'about': 42,
 'no': 43,
 'them': 44,
 'know': 45,
 'like': 46,
 'were': 47,
 'would': 48,
 'went': 49,
 'again': 50,
 'herself': 51,
 'do': 52,
 'have': 53,
 'when': 54,
 'or': 55,
 'could': 56,
 'there': 57,
 'thought': 58,
 'off': 59,
 'time': 60,
 'how': 61,
 'queen': 62,
 'into': 63,
 'see': 64,
 'me': 65,
 'well': 66,
 'did': 67,
 'your': 68,
 'who': 69,
 "don't": 70,
 'king': 71,
 'now': 72,
 "i'm": 73,
 'by': 74,
 'began': 75,
 'my': 76,
 'its': 77,
 'an': 78,
 "it's": 79,
 'turtle': 80,
 'way': 81,
 'mock': 

In [ ]:
for sentence in content.split('\n'):
  print(tokenizer.texts_to_sequences([sentence])[0])

[278, 423, 12, 699]
[]
[278, 423, 12, 699]
[]
[1490, 1491]
[]
[1, 1492, 1493, 1494, 1495, 1496]
[]
[]
[]
[]
[308, 10]
[]
[37, 1, 103, 605]
[]
[]
[11, 14, 255, 4, 104, 27, 478, 8, 353, 74, 17, 424]
[19, 1, 847, 3, 8, 354, 131, 4, 52, 132, 55, 606, 6, 22]
[848, 63, 1, 327, 17, 424, 14, 849, 23, 7, 22, 43]
[700, 55, 1497, 12, 7, 3, 29, 35, 1, 213, 8, 5, 327, 2]
[58, 11, 170, 700, 55, 355, 2]
[]
[25, 6, 14, 850, 12, 17, 356, 328, 16, 66, 16, 6, 56]
[24, 1, 479, 154, 148, 17, 425, 27, 607, 3, 544, 329]
[1, 1081, 8, 426, 5, 1498, 1499, 48, 26, 701, 1, 545]
[8, 190, 38, 3, 1082, 1, 1500, 54, 279, 5, 149]
[103, 21, 1501, 155, 231, 280, 74, 17]
[]
[57, 14, 131, 25, 27, 1083, 12, 15, 851, 67, 11]
[87, 7, 25, 27, 90, 34, 8, 1, 81, 4, 256, 1, 103, 91, 4]
[257, 106, 156, 106, 156, 10, 174, 26, 546, 2, 54, 6, 58]
[7, 115, 1084, 7, 1085, 4, 17, 15, 6, 258, 4, 53]
[1502, 18, 30, 23, 18, 1, 60, 7, 20, 163, 83, 702]
[23, 54, 1, 103, 1503, 180, 5, 427, 34, 8, 77, 1086]
[480, 3, 107, 18, 7, 3, 41, 330, 19

In [ ]:
# create the training data
vectors = []
for sentence in content.split('\n'):
   vectors.append(tokenizer.texts_to_sequences([sentence])[0])

In [ ]:
vectors

[[278, 423, 12, 699],
 [],
 [278, 423, 12, 699],
 [],
 [1490, 1491],
 [],
 [1, 1492, 1493, 1494, 1495, 1496],
 [],
 [],
 [],
 [],
 [308, 10],
 [],
 [37, 1, 103, 605],
 [],
 [],
 [11, 14, 255, 4, 104, 27, 478, 8, 353, 74, 17, 424],
 [19, 1, 847, 3, 8, 354, 131, 4, 52, 132, 55, 606, 6, 22],
 [848, 63, 1, 327, 17, 424, 14, 849, 23, 7, 22, 43],
 [700, 55, 1497, 12, 7, 3, 29, 35, 1, 213, 8, 5, 327, 2],
 [58, 11, 170, 700, 55, 355, 2],
 [],
 [25, 6, 14, 850, 12, 17, 356, 328, 16, 66, 16, 6, 56],
 [24, 1, 479, 154, 148, 17, 425, 27, 607, 3, 544, 329],
 [1, 1081, 8, 426, 5, 1498, 1499, 48, 26, 701, 1, 545],
 [8, 190, 38, 3, 1082, 1, 1500, 54, 279, 5, 149],
 [103, 21, 1501, 155, 231, 280, 74, 17],
 [],
 [57, 14, 131, 25, 27, 1083, 12, 15, 851, 67, 11],
 [87, 7, 25, 27, 90, 34, 8, 1, 81, 4, 256, 1, 103, 91, 4],
 [257, 106, 156, 106, 156, 10, 174, 26, 546, 2, 54, 6, 58],
 [7, 115, 1084, 7, 1085, 4, 17, 15, 6, 258, 4, 53],
 [1502, 18, 30, 23, 18, 1, 60, 7, 20, 163, 83, 702],
 [23, 54, 1, 103, 1503

In [ ]:
inputs = []
outputs = []

for sentence in vectors:
  if len(sentence)>1:
    for i in range(len(sentence)-1):
      inputs.append(sentence[:i+1])
      outputs.append(sentence[i+1])

print(inputs)
print(outputs)

[[278], [278, 423], [278, 423, 12], [278], [278, 423], [278, 423, 12], [1490], [1], [1, 1492], [1, 1492, 1493], [1, 1492, 1493, 1494], [1, 1492, 1493, 1494, 1495], [308], [37], [37, 1], [37, 1, 103], [11], [11, 14], [11, 14, 255], [11, 14, 255, 4], [11, 14, 255, 4, 104], [11, 14, 255, 4, 104, 27], [11, 14, 255, 4, 104, 27, 478], [11, 14, 255, 4, 104, 27, 478, 8], [11, 14, 255, 4, 104, 27, 478, 8, 353], [11, 14, 255, 4, 104, 27, 478, 8, 353, 74], [11, 14, 255, 4, 104, 27, 478, 8, 353, 74, 17], [19], [19, 1], [19, 1, 847], [19, 1, 847, 3], [19, 1, 847, 3, 8], [19, 1, 847, 3, 8, 354], [19, 1, 847, 3, 8, 354, 131], [19, 1, 847, 3, 8, 354, 131, 4], [19, 1, 847, 3, 8, 354, 131, 4, 52], [19, 1, 847, 3, 8, 354, 131, 4, 52, 132], [19, 1, 847, 3, 8, 354, 131, 4, 52, 132, 55], [19, 1, 847, 3, 8, 354, 131, 4, 52, 132, 55, 606], [19, 1, 847, 3, 8, 354, 131, 4, 52, 132, 55, 606, 6], [848], [848, 63], [848, 63, 1], [848, 63, 1, 327], [848, 63, 1, 327, 17], [848, 63, 1, 327, 17, 424], [848, 63, 1, 327

In [ ]:
df = pd.DataFrame(
    {"sentence":inputs,
    "next_word":outputs}
)

In [ ]:
df

sentence  next_word
0                                            [278]        423
1                                       [278, 423]         12
2                                   [278, 423, 12]        699
3                                            [278]        423
4                                       [278, 423]         12
...                                            ...        ...
25068                 [2645, 17, 356, 341, 317, 3]          1
25069              [2645, 17, 356, 341, 317, 3, 1]       2646
25070        [2645, 17, 356, 341, 317, 3, 1, 2646]       1471
25071  [2645, 17, 356, 341, 317, 3, 1, 2646, 1471]        811
25072                                          [1]        216

[25073 rows x 2 columns]

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

inputs = pad_sequences(
    inputs,
    maxlen=max(len(seq) for seq in inputs),
    padding='post',
)


In [ ]:
inputs

array([[ 278,    0,    0, ...,    0,    0,    0],
       [ 278,  423,    0, ...,    0,    0,    0],
       [ 278,  423,   12, ...,    0,    0,    0],
       ...,
       [2645,   17,  356, ...,    0,    0,    0],
       [2645,   17,  356, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0]], dtype=int32)

In [ ]:
inputs.shape

(25073, 15)

In [ ]:
outputs = np.array(outputs)

In [ ]:
print(type(inputs))
print(type(outputs))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
vocab_size = len(tokenizer.word_index) + 1
print("Tokenizer vocabulary size:", vocab_size)

unique_targets = len(set(outputs))
print("Unique output classes:", unique_targets)

Tokenizer vocabulary size: 2647
Unique output classes: 2504


In [ ]:
outputs

array([ 423,   12,  699, ..., 1471,  811,  216])

In [ ]:
print(len(outputs))

25073


In [ ]:
print("Min label:", outputs.min())
print("Max label:", outputs.max())

Min label: 1
Max label: 2646


In [ ]:
from tensorflow.keras.utils import to_categorical
outputs_ohe = to_categorical(outputs , num_classes=2647)

In [ ]:
outputs_ohe

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
print(inputs.shape)
print(outputs.shape)

(25073, 15)
(25073,)


In [ ]:
# architecture

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Flatten,LSTM

model = Sequential()
model.add(Embedding(input_dim = 2647,output_dim = 128,input_length = 15))
model.add(LSTM(150))
model.add(Dense(2647,activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(loss='categorical_crossentropy' , optimizer='adam' , metrics = ['accuracy'])

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(inputs,outputs_ohe ,epochs=100)

Epoch 1/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.0549 - loss: 6.3628
Epoch 2/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.0610 - loss: 5.9534
Epoch 3/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.0598 - loss: 5.9388
Epoch 4/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.0642 - loss: 5.9100
Epoch 5/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.0600 - loss: 5.9278
Epoch 6/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.0621 - loss: 5.9059
Epoch 7/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.0609 - loss: 5.8925
Epoch 8/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.0603 - loss: 5.8775
Epoch 9/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.0643 - loss: 5.7646
Epoch 10/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.0651 - loss: 5.5831
Epoch 11/100
784/784 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.0779 - loss: 5.4507
Epoch 12/100
784/784 ━━━━━━━━━━━━━━━

In [97]:
def testing(test_word):
  test_word_tokenized=tokenizer.texts_to_sequences([test_word])[0]
  padded_test_word = pad_sequences([test_word_tokenized],maxlen =max(len(seq) for seq in inputs),padding='post')

  pred_prob = model.predict(padded_test_word)
  pred_id = np.argmax(pred_prob)


  for key,value in tokenizer.word_index.items():
    if value == pred_id:
      return key

In [98]:
test_sentences=[
    "alice was beginning to get very",

"the rabbit hole went straight on like a",

"she was considering in her own mind",

"the white rabbit was still in sight hurrying down",

"suddenly alice found herself falling down a very",

"the caterpillar and alice looked at each",

"the queen of hearts shouted at the top of her",

"cheshire cat appeared in the branches of a",

"alice opened the door and saw a beautiful",

"the mad hatter was sitting at a large",
]

In [102]:
for i in test_sentences:
  print("input : ",i)
  print("next_word : ",testing(i))

input :  alice was beginning to get very
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
next_word :  tired
input :  the rabbit hole went straight on like a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
next_word :  tunnel
input :  she was considering in her own mind
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
next_word :  sobbing
input :  the white rabbit was still in sight hurrying down
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
next_word :  the
input :  suddenly alice found herself falling down a very
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
next_word :  nervous
input :  the caterpillar and alice looked at each
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
next_word :  other
input :  the queen of hearts shouted at the top of her
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
next_word :  mouth
input :  cheshire cat appeared in the branches of a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
next_word :  low
input :  alice opened the door and saw a beautiful
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
next_word :  alice
input :  the mad hatter wa